//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.15
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_YiuRMNyrd"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "2q4v5i4fml7tk44nt0i8okqb3l"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1ff1ghvqnr2b7e1eb9fdp2p8j2idk2mnkemddgunq5vc6ptr3s7g"
